name: ci

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:

    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v3

    # - name: Cache cache directory
    #   uses: actions/cache@v1
    #   env:
    #     cache-name: cache-cache-dir
    #   with:
    #     path: ~/.cache
    #     key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.python-version }}
    #     restore-keys: |
    #       ${{ runner.os }}-build-${{ env.cache-name }}-
    #       ${{ runner.os }}-build-
    #       ${{ runner.os }}-
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Install main
      run: |
        pip install -e .
    - name: Flake8
      run: |
        pip install importlib-metadata < 5
        pip install hacking
        flake8 .
    - name: Black
      run: |
        pip install black
        black --check .
    - name: Test with pytest
      run: |
        pip install pytest
        pip install torch torchvision
        pip install numba
        pytest tests

    # - name: Install from dist
    #   run: |
    #     rm -f dist/*.tar.gz
    #     python setup.py sdist
    #     pip install dist/*.tar.gz
